version: "3.9"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    container_name: web
    ports: ["5173:5173"]
    environment:
      VITE_BFF_BASE_URL: "http://localhost:8080"
    depends_on:
      - bff
    networks:
      - sw-net
    volumes:
      - ./services/web:/app
      - web_node_modules:/app/node_modules
    command: >
      sh -lc "
        if [ ! -d node_modules ] || [ ! -f node_modules/.install.stamp ]; then
          echo 'Installing web deps (npm ci)...';
          rm -rf node_modules;
          npm ci && date > node_modules/.install.stamp;
        fi;
        npm run dev -- --host 0.0.0.0 --port 5173
      "

  bff:
    build:
      context: ./services/bff
      dockerfile: Dockerfile
    container_name: bff
    env_file: [./env/bff.env]
    ports: ["8080:8080"]
    depends_on:
      - starwars
      - statistics
      - rabbitmq
      - redis
    networks:
      - sw-net

  starwars:
    build:
      context: ./services/starwars-service
      dockerfile: Dockerfile
    container_name: starwars-service
    env_file: [./env/starwars-service.env]
    ports: ["8081:8081"]
    depends_on:
      - rabbitmq
      - redis
    networks:
      - sw-net

  statistics:
    build:
      context: ./services/statistics-service
      dockerfile: Dockerfile
    container_name: statistics-service
    env_file: [./env/statistics-service.env]
    ports: ["8082:8082"]
    depends_on:
      - db
      - rabbitmq
    networks:
      - sw-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - sw-net

  db:
    image: postgres:16
    container_name: postgres
    env_file: [./env/db.env]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sw-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sw-net

networks:
  sw-net:

volumes:
  pgdata:
  web_node_modules:
